version: '2'

services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: database
    environment:
      - POSTGRES_DB=ggdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./backups:/home/backups